export const componentRegistry = [
  {
    id: "button",
    layer: "primitive",
    summary: "受控按钮，用于页面级、筛选区、结果集和弹层底部动作。",
    usage: ["页面级动作", "筛选动作", "结果集动作", "弹层底部动作"],
    allows: ["variant", "disabled", "loading", "block", "children", "onClick"],
    forbids: ["直接暴露完整底层 Button API"],
  },
  {
    id: "select-field",
    layer: "primitive",
    summary: "受控选择字段，用于筛选区和轻量结构化选择。",
    usage: ["筛选字段", "轻量结构化选择"],
    allows: [
      "options",
      "placeholder",
      "value",
      "defaultValue",
      "width",
      "disabled",
      "onValueChange",
    ],
    forbids: ["远程搜索", "复杂下拉容器控制", "多模式组合能力"],
  },
  {
    id: "date-field",
    layer: "primitive",
    summary: "受控日期字段，用于筛选和基础日期输入。",
    usage: ["日期筛选", "基础日期输入"],
    allows: ["value", "defaultValue", "width", "disabled", "min", "max", "onChange"],
    forbids: ["复杂日期面板控制", "范围快捷策略", "底层弹层控制"],
  },
  {
    id: "status-tag",
    layer: "primitive",
    summary: "状态标签，屏蔽底层颜色细节。",
    usage: ["状态展示", "分类标记"],
    allows: ["tone", "children"],
    forbids: ["任意自定义颜色", "任意样式覆盖"],
  },
  {
    id: "data-table",
    layer: "primitive",
    summary: "原型阶段表格载体。",
    usage: ["列表页主数据区", "结构化结果展示"],
    allows: ["columns", "rows", "emptyText"],
    forbids: ["scroll", "expandable", "rowSelection", "sorter", "filters", "virtual"],
  },
  {
    id: "panel",
    layer: "primitive",
    summary: "统一 Surface 容器。",
    usage: ["需要视觉边界的容器", "功能模块包裹"],
    allows: ["title", "extra", "children"],
    forbids: ["多层重 Surface 技术开关", "任意视觉变体扩散"],
  },
  {
    id: "modal",
    layer: "primitive",
    summary: "受控弹层容器。",
    usage: ["弹层任务", "局部确认与阅读"],
    allows: ["open", "title", "footer", "children", "onClose"],
    forbids: ["挂载容器控制", "动画生命周期控制", "任意尺寸系统"],
  },
] as const;
