export const compositionRegistry = [
  {
    id: "page-header",
    layer: "composition",
    pageTypes: ["list", "form", "detail"],
    regions: ["header"],
    summary: "页面标题区与顶层动作。",
    usage: ["页面标题", "页面身份信息", "影响整个页面的顶层动作"],
    allows: ["title", "description", "actions"],
  },
  {
    id: "filter-bar",
    layer: "composition",
    pageTypes: ["list"],
    regions: ["filter"],
    summary: "查询条件与查询动作。",
    usage: ["筛选结果集", "轻量收窄条件", "高级筛选展开"],
    allows: ["fields", "actions"],
  },
  {
    id: "action-bar",
    layer: "composition",
    pageTypes: ["list"],
    regions: ["action"],
    summary: "结果集相关页面级操作。",
    usage: ["批量处理", "导出", "视图切换", "辅助工具"],
    allows: ["primary", "secondary", "tools"],
  },
  {
    id: "detail-section",
    layer: "composition",
    pageTypes: ["detail"],
    regions: ["detail"],
    summary: "单对象详情阅读区。",
    usage: ["详情字段分组", "说明信息", "过程信息"],
    allows: ["title", "description", "items", "sections"],
  },
  {
    id: "summary-strip",
    layer: "composition",
    pageTypes: ["detail", "dashboard"],
    regions: ["summary"],
    summary: "页面顶部关键摘要条。",
    usage: ["摘要指标", "关键状态总览"],
    allows: ["items"],
  },
] as const;
